<?php 
        include("head.php");
        include("nav-top.php");
        include("header.php");
        include("slider.php");           
        include("nav-bot.php");           
        include("main.php");                  
        include("footer.php");         
?>
